# Generated by Django 3.2.9 on 2021-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otto", "0002_shipment"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW otto_orderitem_stats AS
            SELECT
                row_number() OVER (PARTITION BY true) AS id,
                DATE_TRUNC('month', created) AS month,
                fulfillment_status AS status,
                COUNT(id) AS count,
                SUM(price_in_cent)::float/100 AS revenue
            FROM
                otto_orderitem
            GROUP BY
                month,
                fulfillment_status
            ORDER BY
                month
        """
        )
    ]
