# Generated by Django 4.1.5 on 2023-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otto", "0004_statsorderitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
