# Generated by Django 3.2.6 on 2021-09-03 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0003_pricetool_ongoing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricetool",
            old_name="ongoing",
            new_name="active",
        ),
    ]
