# Generated by Django 4.0.2 on 2022-06-16 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0022_rename_costs_zcosts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ZCosts",
            new_name="ZCost",
        ),
    ]
