# Generated by Django 4.0.2 on 2022-07-15 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0026_remove_salesreportimport_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawdailyshipmentreport",
            name="article_number",
        ),
        migrations.AddField(
            model_name="rawdailyshipmentreport",
            name="zproduct",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="zalando.zproduct",
            ),
            preserve_default=False,
        ),
    ]
