# Generated by Django 4.1.5 on 2023-02-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_marketplaceconfig_alter_article_options_and_more"),
        ("zalando", "0030_zproduct_pimped"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawdailyshipmentreport",
            name="zproduct",
        ),
        migrations.AddField(
            model_name="rawdailyshipmentreport",
            name="price",
            field=models.ForeignKey(
                default="AWHoodie-BO-XL",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.price",
            ),
            preserve_default=False,
        ),
    ]
