# Generated by Django 4.1.5 on 2023-02-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_marketplaceconfig_alter_article_options_and_more"),
        ("zalando", "0031_remove_rawdailyshipmentreport_zproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdailyshipmentreport",
            name="marketplace_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.marketplaceconfig",
            ),
        ),
    ]
