# Generated by Django 5.0 on 2024-01-12 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0033_feedupload_validation_result"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesReport",
        ),
    ]
