# Generated by Django 5.0 on 2024-01-12 05:02

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0034_delete_salesreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "Euro")], default="EUR", max_length=3
                    ),
                ),
                ("ean", models.CharField(max_length=16)),
                ("order_date", models.DateTimeField()),
                ("order_number", models.BigIntegerField()),
                ("pai_fee", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "payment_service_fee",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("shipment_subtype", models.CharField(max_length=32)),
                ("shipment_type", models.CharField(max_length=32)),
                ("shipping_return_date", models.DateTimeField()),
                (
                    "import_reference",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zalando.salesreportimport",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
