# Generated by Django 5.0 on 2024-01-12 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0035_salesreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesreportimport",
            name="month",
        ),
    ]
