# Generated by Django 5.0 on 2024-01-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0039_alter_salesreportfileupload_original_csv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesreport",
            name="import_reference",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zalando.salesreportfileupload",
            ),
        ),
    ]
