# Generated by Django 5.0 on 2024-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0041_salesreport_zalando_marketplace_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesreport",
            name="ean",
            field=models.CharField(max_length=13),
        ),
    ]
