# Generated by Django 5.0 on 2024-02-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0042_alter_salesreport_ean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesreport",
            name="import_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zalando.salesreportfileupload",
            ),
        ),
    ]
