# Generated by Django 5.2.7 on 2026-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalando', '0043_alter_salesreport_import_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedupload',
            name='path_to_pp_csv',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
