# Generated by Django 4.0.2 on 2022-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_ean_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
