# Generated by Django 4.1.5 on 2023-04-25 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="error_msg",
        ),
    ]
