# Generated by Django 5.0 on 2024-01-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_price_ean"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="zalando_marketplace_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.marketplaceconfig",
            ),
        ),
    ]
