# Generated by Django 5.1.5 on 2025-02-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_salesstatstop13_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesStatsReturnTop13",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("category_name", models.CharField(max_length=100)),
                ("returned", models.IntegerField()),
            ],
            options={
                "db_table": "core_salesstats_top13_return_view",
                "managed": False,
            },
        ),
    ]
