# Generated by Django 5.1.7 on 2025-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_salesvolumezalando"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="vk_aboutyou",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
