# Generated by Django 5.1.7 on 2025-03-29 21:19

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiktok", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("city", models.CharField(max_length=32)),
                ("country_code", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("first_name", models.CharField(max_length=64)),
                ("full_address", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=64)),
                ("street", models.CharField(max_length=128)),
                ("zip_code", models.CharField(max_length=32)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("tracking_number", models.CharField(max_length=128)),
                ("package_id", models.CharField(max_length=128)),
                ("response_status_code", models.IntegerField(null=True)),
                ("response", models.TextField(null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("ON_HOLD", "On Hold"),
                            ("AWAITING_SHIPMENT", "Awaiting Shipment"),
                            ("PARTIALLY_SHIPPING", "Partially Shipping"),
                            ("AWAITING_COLLECTION", "Awaiting Collection"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("buyer_email", models.EmailField(max_length=254)),
                ("tiktok_order_id", models.CharField(max_length=24)),
                ("create_time", models.DateTimeField()),
                ("rts_sla_time", models.DateTimeField()),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_address_set",
                        to="tiktok.address",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("tiktok_orderitem_id", models.CharField(max_length=24)),
                ("tiktok_sku_id", models.CharField(max_length=24)),
                ("tiktok_product_name", models.CharField(max_length=128)),
                ("package_id", models.CharField(max_length=128)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sku", models.CharField(max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("ON_HOLD", "On Hold"),
                            ("AWAITING_SHIPMENT", "Awaiting Shipment"),
                            ("PARTIALLY_SHIPPING", "Partially Shipping"),
                            ("AWAITING_COLLECTION", "Awaiting Collection"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tiktok.order"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
