# Generated by Django 5.1.7 on 2025-05-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutyou", "0002_address_order_orderitem_shipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_fee",
        ),
    ]
