# Generated by Django 5.1.7 on 2025-05-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutyou", "0003_remove_order_delivery_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="email",
        ),
        migrations.AlterField(
            model_name="order",
            name="marketplace_order_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
