# Generated by Django 5.1.7 on 2025-05-20 04:08

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutyou", "0005_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchRequestTrackingInfo",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=32, null=True)),
                ("tracking_info", models.CharField(max_length=256, null=True)),
                ("response", models.JSONField(null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
