# Generated by Django 5.1.7 on 2025-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutyou", "0006_batchrequesttrackinginfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchrequesttrackinginfo",
            options={"verbose_name_plural": "BatchRequestsTrackingInfo"},
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("shipped", "Shipped"),
                    ("cancelled", "Canceled"),
                    ("returned", "Returned"),
                ],
                default="open",
                max_length=11,
            ),
        ),
    ]
