# Generated by Django 5.1.5 on 2025-10-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutyou", "0007_alter_batchrequesttrackinginfo_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchrequesttrackinginfo",
            name="tracking_info",
        ),
    ]
