# Generated by Django 3.2.8 on 2021-10-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0002_authrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='code_challenge',
            field=models.CharField(max_length=128),
        ),
    ]
