# Generated by Django 3.2.8 on 2021-10-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0006_authrequest2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authrequest2',
            old_name='auth_code',
            new_name='refresh_token',
        ),
    ]
