# Generated by Django 3.2.9 on 2021-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0013_shipment"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW etsy_orderitem_stats AS
            SELECT
                row_number() OVER (PARTITION BY true) AS id,
                DATE_TRUNC('month', created) AS month,
                fulfillment_status AS status,
                COUNT(id) AS count,
                SUM(price_in_cent)::float/100 AS revenue
            FROM
                etsy_orderitem
            GROUP BY
                month,
                fulfillment_status
            ORDER BY
                month
        """
        ),
        migrations.CreateModel(
            name="StatsOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateTimeField()),
                ("status", models.CharField(max_length=16)),
                ("count", models.IntegerField()),
                ("revenue", models.FloatField()),
            ],
            options={
                "db_table": "etsy_orderitem_stats",
                "managed": False,
            },
        ),
    ]
