# Generated by Django 3.2.9 on 2022-01-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0014_statsorderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
