# Generated by Django 4.1.5 on 2023-03-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0016_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="marketplace_order_number",
        ),
    ]
