# Generated by Django 5.2.7 on 2026-05-22 11:34

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('feed_type', models.CharField(choices=[('full', 'Full'), ('delta', 'Delta')], default='full', max_length=8)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('number_of_items', models.PositiveIntegerField()),
                ('path_to_csv', models.CharField(max_length=256)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('booking_id', models.IntegerField(unique=True)),
                ('order_id', models.IntegerField()),
                ('marketplace_name', models.CharField(max_length=64)),
                ('marketplace_detail', models.CharField(blank=True, default='', max_length=64)),
                ('marketplace_order_id_1', models.CharField(max_length=128)),
                ('marketplace_order_id_2', models.CharField(blank=True, default='', max_length=128)),
                ('order_date', models.DateTimeField()),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('buyer_country', models.CharField(blank=True, default='', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('exported', models.BooleanField(default=False)),
                ('origin_labels', models.CharField(blank=True, default='', max_length=16)),
                ('origin_documents', models.CharField(blank=True, default='', max_length=16)),
                ('origin_invoices', models.CharField(blank=True, default='', max_length=16)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('line_id', models.IntegerField(unique=True)),
                ('item_id', models.IntegerField()),
                ('line_identifier', models.CharField(blank=True, default='', max_length=64)),
                ('marketplace_sku', models.CharField(blank=True, default='', max_length=128)),
                ('article_number', models.CharField(blank=True, default='', max_length=64)),
                ('price', models.CharField(max_length=16)),
                ('price_net', models.CharField(blank=True, default='', max_length=16)),
                ('vat', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=16)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='irisone.order')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
