# Generated by Django 5.2.7 on 2026-05-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedupload',
            name='feed_type',
            field=models.CharField(choices=[('full', 'Full'), ('delta', 'Delta'), ('product', 'Product')], default='full', max_length=10),
        ),
    ]
