# Generated by Django 4.2.5 on 2023-09-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceTool",
        ),
        migrations.RemoveField(
            model_name="feedupload",
            name="g_factor",
        ),
        migrations.RemoveField(
            model_name="feedupload",
            name="number_of_valid_items",
        ),
        migrations.AddField(
            model_name="feedupload",
            name="path_to_pimped_xlsx",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
