# Generated by Django 3.2.6 on 2021-09-02 05:02

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("status_code_validation", models.PositiveSmallIntegerField()),
                ("status_code_feed_upload", models.PositiveSmallIntegerField()),
                ("number_of_valid_items", models.PositiveIntegerField()),
                ("path_to_original_csv", models.CharField(max_length=128)),
                ("path_to_pimped_csv", models.CharField(max_length=128)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
