# Generated by Django 3.2.6 on 2021-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0002_pricetool"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricetool",
            name="ongoing",
            field=models.BooleanField(default=False),
        ),
    ]
