# Generated by Django 3.2.6 on 2021-09-16 03:52

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zalando", "0005_feedupload_z_factor"),
    ]

    operations = [
        migrations.CreateModel(
            name="OEAWebhookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("payload", models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="oeawebhookmessage",
            index=models.Index(
                fields=["created"], name="zalando_oea_created_eda8f7_idx"
            ),
        ),
    ]
