# Generated by Django 4.0.2 on 2022-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zalando", "0012_transactionfileupload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionfileupload",
            name="month",
        ),
        migrations.AddField(
            model_name="transactionfileupload",
            name="file_name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
