# Generated by Django 4.0.2 on 2022-06-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_product_category'),
        ('zalando', '0019_alter_zproduct_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
    ]
