# Generated by Django 4.0.2 on 2022-06-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zalando', '0021_costs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costs',
            new_name='ZCosts',
        ),
    ]
