# Generated by Django 4.0.2 on 2022-07-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zalando", "0024_rawdailyshipmentreport_delete_zcalculator"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreport",
            name="import_reference",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zalando.salesreportimport",
            ),
        ),
    ]
