# Generated by Django 5.0 on 2024-01-12 05:13

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0036_remove_salesreportimport_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReportFileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                (
                    "original_csv",
                    models.FileField(upload_to="zalando/finance/monthly_sales_reports"),
                ),
                ("file_name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "zalando_monthly_sales_report_file_upload",
            },
        ),
        migrations.AlterModelOptions(
            name="salesreport",
            options={},
        ),
        migrations.AlterModelTable(
            name="salesreport",
            table="zalando_monthly_sales_report",
        ),
    ]
