# Generated by Django 5.0 on 2024-01-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0037_salesreportfileupload_alter_salesreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesreportfileupload",
            name="file_name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
