# Generated by Django 5.0 on 2024-01-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zalando", "0038_alter_salesreportfileupload_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesreportfileupload",
            name="original_csv",
            field=models.FileField(
                max_length=128, upload_to="zalando/finance/monthly_sales_reports"
            ),
        ),
    ]
