from decimal import Decimal

# Aufwandskonto Gebühren Onlinehandel (mit/ohne USt ?)
ACCOUNT_ONLINE_FEE = 3101
# Erlöse 19% für Zielland Dtld.
NINETEEN_PERCENT_GERMANY = 8400
# Erlöse 19% Zalando
NINETEEN_PERCENT_GERMANY_ZALANDO = 8402
# Verrechnungskonto Zalando
ZALANDO_OFFSET_ACCOUNT = 12800
# 19% Märchensteuer
NINETEEN_PERCENT_VAT = Decimal(1.19)

SKU_BLACKLIST = [
    "iron_dude_w-xs",
    "iron_dude_w-s",
    "iron_dude_w-m",
    "iron_dude_w-l",
    "iron_dude_w-xl",
    "iron_dude_w-xxl",
    "anti_barista_w-xs",
    "anti_barista_w-s",
    "anti_barista_w-m",
    "anti_barista_w-l",
    "anti_barista_w-xl",
    "anti_barista_w-xxl",
    "anti_turista_w-xs",
    "anti_turista_w-s",
    "anti_turista_w-m",
    "anti_turista_w-l",
    "anti_turista_w-xl",
    "anti_turista_w-xxl",
    "donut_rain_w-xs",
    "donut_rain_w-s",
    "donut_rain_w-m",
    "donut_rain_w-l",
    "donut_rain_w-xl",
    "donut_rain_w-xxl",
    "eat_shit_w-xs",
    "eat_shit_w-s",
    "eat_shit_w-m",
    "eat_shit_w-l",
    "eat_shit_w-xl",
    "eat_shit_w-xxl",
    "eyeofthe13_w-xs",
    "eyeofthe13_w-s",
    "eyeofthe13_w-m",
    "eyeofthe13_w-l",
    "eyeofthe13_w-xl",
    "eyeofthe13_w-xxl",
    "hamwich_w-xs",
    "hamwich_w-s",
    "hamwich_w-m",
    "hamwich_w-l",
    "hamwich_w-xl",
    "hamwich_w-xxl",
    "mt_w-xs",
    "mt_w-s",
    "mt_w-m",
    "mt_w-l",
    "mt_w-xl",
    "mt_w-xxl",
    "pixelate_w-xs",
    "pixelate_w-s",
    "pixelate_w-m",
    "pixelate_w-l",
    "pixelate_w-xl",
    "pixelate_w-xxl",
    "pizza_1_w-xs",
    "pizza_1_w-s",
    "pizza_1_w-m",
    "pizza_1_w-l",
    "pizza_1_w-xl",
    "pizza_1_w-xxl",
    "pizza_2_w-xs",
    "pizza_2_w-s",
    "pizza_2_w-m",
    "pizza_2_w-l",
    "pizza_2_w-xl",
    "pizza_2_w-xxl",
    "rich_kids_w-xs",
    "rich_kids_w-s",
    "rich_kids_w-m",
    "rich_kids_w-l",
    "rich_kids_w-xl",
    "rich_kids_w-xxl",
    "riot_pixel_w-xs",
    "riot_pixel_w-s",
    "riot_pixel_w-m",
    "riot_pixel_w-l",
    "riot_pixel_w-xl",
    "riot_pixel_w-xxl",
    "riot_police_w-xs",
    "riot_police_w-s",
    "riot_police_w-m",
    "riot_police_w-l",
    "riot_police_w-xl",
    "riot_police_w-xxl",
    "stra_wings_w-xs",
    "stra_wings_w-s",
    "stra_wings_w-m",
    "stra_wings_w-l",
    "stra_wings_w-xl",
    "stra_wings_w-xxl",
    "wiener_guy_w-xs",
    "wiener_guy_w-s",
    "wiener_guy_w-m",
    "wiener_guy_w-l",
    "wiener_guy_w-xl",
    "wiener_guy_w-xxl",
    "taco_love_w-xs",
    "taco_love_w-s",
    "taco_love_w-m",
    "taco_love_w-l",
    "taco_love_w-xl",
    "taco_love_w-xxl",
    "wood_fries_w-xs",
    "wood_fries_w-s",
    "wood_fries_w-m",
    "wood_fries_w-l",
    "wood_fries_w-xl",
    "wood_fries_w-xxl",
]
