# Generated by Django 3.2.8 on 2021-10-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etsy", "0004_alter_authrequest_verifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authrequest",
            name="code_challenge",
            field=models.BinaryField(max_length=128),
        ),
        migrations.AlterField(
            model_name="authrequest",
            name="verifier",
            field=models.BinaryField(max_length=256),
        ),
    ]
