# Generated by Django 5.0 on 2024-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etsy", "0018_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="buyer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
