# Generated by Django 5.0 on 2024-03-28 05:03

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otto", "0005_address_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("sku", models.CharField(max_length=32)),
                ("ean", models.CharField(max_length=16)),
                ("position_item_id", models.CharField(max_length=64)),
                ("order_number", models.CharField(max_length=16)),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("ANNOUNCED", "Announced"),
                            ("PROCESSABLE", "Processable"),
                            ("SENT", "Sent"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED_BY_PARTNER", "Cancelled By Partner"),
                            ("CANCELLED_BY_MARKETPLACE", "Cancelled By Marketplace"),
                        ],
                        max_length=24,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("last_modified", models.DateTimeField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
