# Generated by Django 5.0.6 on 2024-08-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otto", "0006_orderitemjournal"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemjournal",
            name="order_date",
            field=models.DateTimeField(null=True),
        ),
    ]
