# Generated by Django 4.0.2 on 2022-06-01 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["sku"]},
        ),
    ]
