# Generated by Django 4.1.5 on 2023-01-24 16:57

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "article",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                (
                    "costs_production",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "vk_zalando",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "vk_otto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "z_shipping_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=3.55,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "z_return_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=3.55,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "o_shipping_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=3.55,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "o_return_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=3.55,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.category",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
