# Generated by Django 4.1.5 on 2023-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="error",
            name="comment",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
