# Generated by Django 4.1.5 on 2023-06-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_error_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="pimped_zalando",
            field=models.BooleanField(default=False),
        ),
    ]
