# Generated by Django 5.0 on 2024-01-20 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_price_zalando_marketplace_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="zalando_marketplace_config",
        ),
    ]
