# Generated by Django 5.1.5 on 2025-02-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_salesstats"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesStats",
        ),
    ]
