# Generated by Django 5.1.5 on 2025-02-01 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_salesstatstop13"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="salesstatstop13",
            table="core_salesstats_top13_view",
        ),
    ]
