# Generated by Django 5.1.5 on 2025-02-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_salesstatsreturntop13"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesVolumeZalando",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum_sales", models.CharField(max_length=100)),
                ("day", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "core_sales_volume_zalando_view",
                "managed": False,
            },
        ),
    ]
