# Generated by Django 4.0.2 on 2022-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirapodo", "0002_rename_tb_id_orderitem_position_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="ean",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
