# Generated by Django 4.1.5 on 2023-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirapodo", "0006_orderitem_internal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(max_length=32),
        ),
    ]
