# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 18:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=512)),
                ('sku', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('asin', models.CharField(max_length=32)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_time', models.DateTimeField()),
                ('_type', models.CharField(max_length=64)),
                ('order_id', models.CharField(blank=True, max_length=32, null=True)),
                ('sku', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=64, null=True)),
                ('dispatch_type', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True)),
                ('turnover', models.DecimalField(decimal_places=2, help_text='Umsatz', max_digits=12)),
                ('voucher_shipping_costs', models.DecimalField(decimal_places=2, help_text='Gutschrift für Versandkosten', max_digits=12)),
                ('charge', models.DecimalField(decimal_places=2, help_text='Verkaufsgebühren', max_digits=12)),
                ('charge_fba', models.DecimalField(decimal_places=2, help_text='Gebühren zu Versand durch Amazon', max_digits=12)),
                ('charge_other', models.DecimalField(decimal_places=2, help_text='Andere Transaktionsgebühren', max_digits=12)),
                ('other', models.DecimalField(decimal_places=2, help_text='Andere', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Gesamt', max_digits=16)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'verbose_name': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='ProductDescriptionDE',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sale.Product')),
                ('description', models.CharField(max_length=16384)),
            ],
        ),
    ]
