# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20160905_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRankHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_rank', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Product')),
            ],
        ),
    ]
