# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20161015_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRankHistoryByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salesrank', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
