# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_salesrankhistorybyday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_time', models.DateField()),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sku',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Product'),
        ),
        migrations.AlterField(
            model_name='salesrankhistorybyday',
            name='_time',
            field=models.DateTimeField(),
        ),
    ]
