# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20161028_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
