# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20161118_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
