# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20161118_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Product')),
            ],
        ),
    ]
