# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_productmarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmarker',
            name='action_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productmarker',
            name='global_event',
            field=models.BooleanField(default=False),
        ),
    ]
