# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20170318_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmarker',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sale.Category'),
            preserve_default=False,
        ),
    ]
