[tool.pytest.ini_options]
pythonpath = [
  "."
]

[pytest]
# DJANGO_SETTINGS_MODULE = m13.config.develop
python_files = ["test_*.py"]

[tool.isort]
profile = "black"


[tool.pylint."MESSAGES CONTROL"]
disable = '''logging-fstring-interpolation,
  not-an-iterable,
  missing-module-docstring,
'''