[tool.pytest.ini_options]
pythonpath = [
  "."
]

[pytest]
# DJANGO_SETTINGS_MODULE = m13.config.develop
python_files = ["test_*.py"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120

[tool.pylint.format]
max-line-length = 120

[tool.pylint.MASTER]

# Add files or directories to the blacklist. They should be base names, not
# paths.
ignore = '.git'

# Add files or directories matching the regex patterns to the blacklist. The
# regex matches against base names, not paths.
ignore-paths = [
  '^etsy/migrations/.*$',
  '^galaxus/migrations/.*$',
  '^otto/migrations/.*$',
  '^zalando/migrations/.*$',
]

[tool.pylint."MESSAGES CONTROL"]
disable = '''logging-fstring-interpolation,
  not-an-iterable,
  missing-module-docstring,
'''
